# INI file for rzadams

[MTTDefaults]
scratchdir = v6.0.x_scratch
description = OpenMPI v6.0.x
platform = LLNL-rzadams
executor = sequential
trial = False

[Profile:Installed]

#======================================================================
# Middleware construction phases - get the middleware, build, and
# install it. This isn't a required phase - if the purpose of this test
# is to simply stress the physical system, then one can skip this phase
#======================================================================

[MiddlewareGet:OMPIMaster]
plugin = OMPI_Snapshot
url =  https://download.open-mpi.org/nightly/open-mpi/v6.0.x
version_file = /usr/workspace/hpp/mtt/vf_v6.0.x
mpi_name = ompi-nightly-v6.0.x

#----------------------------------------------------------------------

[MiddlewareBuild:OMPIMaster]
parent = MiddlewareGet:OMPIMaster
plugin = Autotools
configure_options =  --with-ofi --with-rocm=${ENV:ROCM_PATH}  --disable-sphinx --with-pmix=internal --with-flux  --enable-mca-no-build=smsc-knem
make_options = -j 12 install
stderr_save_lines = 100

#======================================================================
# Test construction phases - get and build the tests that the
# target software will run.
#======================================================================

[TestGet:IBM]
plugin = Git
url =  git@github.com:open-mpi/ompi-tests
subdir = ibm
#parent required or test will run even if build failed
parent = MiddlewareBuild:OMPIMaster


[ASIS TestGet:OSU]
plugin = Copytree
src =  /usr/workspace/hpp/osu-micro-benchmarks-7.5.2-mtt
#parent required or test will run even if build failed
parent = MiddlewareBuild:OMPIMaster


#======================================================================
# Test build phase
#======================================================================

[TestBuild:IBMInstalled]
parent = TestGet:IBM
#merge_stdout_stderr = 1
#stderr_save_lines = 100
middleware = MiddlewareBuild:OMPIMaster
autogen_cmd = ./autogen.sh
configure_options = CC=mpicc CXX=mpic++ F77=mpif77 FC=mpifort
make_options = -j 4


[TestBuild:OSUInstalled]
parent = TestGet:OSU
merge_stdout_stderr = 1
stderr_save_lines = 100
middleware = MiddlewareBuild:OMPIMaster
configure_options = CC=mpicc CXX=mpiCC FC=mpifort --enable-rocm --with-rocm=${ENV:ROCM_PATH}
make_options = -j 4
checkpoint_file = /usr/workspace/hpp/mtt/v6.0.x_scratch/ompi_logfile
