# INI file for perlmutter

[MTTDefaults]
scratchdir = v5.0.x_scratch
description = OpenMPI v5.0.x
platform = NERSC-perlmutter
executor = sequential
restart_file = /global/homes/h/hpp/mtt_perlmutter/v5.0.x_scratch/ompi_logfile

#======================================================================
# Reporter phase
#======================================================================

[Reporter: text file backup]
plugin = TextFile
filename = mttresults.txt
summary_footer =
detail_header  =
detail_footer  =
textwrap = 78

#----------------------------------------------------------------------

[Reporter: IU database]
plugin = IUDatabase
realm = OMPI
username = lanl
pwfile = /global/homes/h/hpp/mtt_perlmutter/pw_file
platform = NERSC-perlmutter
url = https://mtt.open-mpi.org/submit/cpy/api/

[Reporter: JunitXML]
plugin = JunitXML
filename = mttresults.xml
textwrap = 78
