# INI file for rzadams

[MTTDefaults]
scratchdir = v6.0.x_scratch
description = OpenMPI v6.0.x
platform = LLNL-rzadams
executor = sequential
restart_file = /usr/workspace/hpp/mtt/v6.0.x_scratch/ompi_logfile

#======================================================================
# Reporter phase
#======================================================================

[Reporter: text file backup]
plugin = TextFile
filename = mttresults.txt
summary_footer =
detail_header  =
detail_footer  =
textwrap = 78

#----------------------------------------------------------------------

[Reporter: IU database]
plugin = IUDatabase
realm = OMPI
username = lanl
pwfile = /usr/workspace/hpp/mtt/pw_file
platform = LLNL-rzadams
url = https://mtt.open-mpi.org/submit/cpy/api/

[Reporter: JunitXML]
plugin = JunitXML
filename = mttresults.xml
textwrap = 78
