# INI file for aurora

[MTTDefaults]
scratchdir = v6.0.x_scratch
description = OpenMPI master
platform = ANL-aurora
executor = sequential
restart_file = /home/howardp/mtt/v6.0.x_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
#command = aprun
command = mpirun
np = 16

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:IBMInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:IBMInstalled
fail_timeout = 120
#test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
test_dir = "pt2pt,collective,random"
checkpoint_file = /home/howardp/mtt/v6.0.x_scratch/ompi_logfile
#test_dir = "communicator, datatype, environment, group, info, io, pt2pt, random, topology"
max_num_tests = 400
stdout_save_lines = 100
stderr_save_lines = 100

# Tests that are supposed to fail
fail_tests = abort:3 final:1

# Tests to skip
skip_tests = comm_idup comm_idup_usempif08 comm_idup_usempi comm_idup_mpifh sendrecv_big sendrecv_rep_big ssend start startall testany mprobe improbe mprobe-mpich mprobe_usempi mprobe_mpifh improbe_usempi mprobe_usempif08 improbe_usempif08 isendrecv_big isendrecv_rep_big isendrecv_rep_big2 isendrecv_f sendrecv_rep_big2 int_overflow iallreduce_nocommute_gap ireduce_nocommute_gap improbe_mpifh bcast_struct scatter_gap iallgather_gap iallreduce_nocommute_gap_in_place ibcast_struct iexscan_nocommute_gap iexscan_nocommute_gap_in_place igather_gap ireduce_nocommute_gap ireduce_nocommute_gap_in_place ireduce_scatter_block_nocommute_gap ireduce_scatter_block_nocommute_gap_in_place iscan_nocommute_gap iscan_nocommute_gap_in_place iscatter_gap ireduce_nocommute_gap_inter ireduce_scatter_nocommute_gap_in_place allgather_gap_inter allreduce_nocommute_gap_inter reduce_scatter_nocommute_gap_inter reduce_scatter_nocommute_gap_inter reduce_scatter_block_nocommute_gap_inter reduce_scatter_block_nocommute_stride_inter iallgather_gap_inter allgather_gap_inter iallgatherv_gap_inter iallreduce_nocommute_gap_inter iallreduce_nocommute_gap_inter igather_gap_inter igatherv_gap_inter igatherv_gap_inter ireduce_nocommute_gap_inter ireduce_scatter_block_nocommute_gap_inter


