# INI file for Polaris

[MTTDefaults]
scratchdir = v5.0.x_scratch
description = OpenMPI master
platform = ANL-sunspot
executor = sequential
restart_file = /home/howardp/mtt/v5.0.x_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
#command = aprun
command = mpirun
np = 16

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:IBMInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:IBMInstalled
fail_timeout = 120
#test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
test_dir = "pt2pt,collective"
checkpoint_file = /home/howardp/mtt/v5.0.x_scratch/ompi_logfile
#test_dir = "communicator, datatype, environment, group, info, io, pt2pt, random, topology"
max_num_tests = 200
stdout_save_lines = 100
stderr_save_lines = 100

# Tests that are supposed to fail
fail_tests = abort:3 final:1

# Tests to skip
skip_tests = sendrecv_rep_big,sendrecv_rep_big2

