# INI file for crusher

[MTTDefaults]
scratchdir = master_scratch
description = OpenMPI main
platform = OLCF-crusher
executor = sequential
restart_file = /ccs/home/howardp/mtt/master_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
command = mpirun
np = 16
options = --display-allocation

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:IBMInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:IBMInstalled
timeout = 180
test_dir = "collective, communicator, pt2pt"
#test_dir = "collective"
checkpoint_file = /ccs/home/howardp/mtt/master_scratch/ompi_logfile
#test_dir = "communicator, datatype, environment, group, info, io, pt2pt, random, topology"
#max_num_tests = 25
stdout_save_lines = 100
stderr_save_lines = 100

# Tests that are supposed to fail
fail_tests = abort:3 final:1

skip_tests = comm_idup comm_idup_usempif08 comm_idup_usempi comm_idup_mpifh sendrecv_big sendrecv_rep_big ssend start startall testany mprobe improbe mprobe-mpich mprobe_usempi mprobe_mpifh improbe_usempi mprobe_usempif08 improbe_usempif08 isendrecv_big isendrecv_rep_big isendrecv_rep_big2 isendrecv_f sendrecv_rep_big2 int_overflow iallreduce_nocommute_gap ireduce_nocommute_gap improbe_mpifh bcast_struct scatter_gap iallgather_gap iallreduce_nocommute_gap_in_place ibcast_struct iexscan_nocommute_gap iexscan_nocommute_gap_in_place igather_gap ireduce_nocommute_gap ireduce_nocommute_gap_in_place ireduce_scatter_block_nocommute_gap ireduce_scatter_block_nocommute_gap_in_place iscan_nocommute_gap iscan_nocommute_gap_in_place iscatter_gap ireduce_nocommute_gap_inter ireduce_scatter_nocommute_gap_in_place allgather_gap_inter allreduce_nocommute_gap_inter reduce_scatter_nocommute_gap_inter reduce_scatter_nocommute_gap_inter reduce_scatter_block_nocommute_gap_inter reduce_scatter_block_nocommute_stride_inter iallgather_gap_inter allgather_gap_inter iallgatherv_gap_inter iallreduce_nocommute_gap_inter iallreduce_nocommute_gap_inter igather_gap_inter igatherv_gap_inter igatherv_gap_inter ireduce_nocommute_gap_inter ireduce_scatter_block_nocommute_gap_inter scatter_gap_inter isend iscatterv_gap_inter ireduce_scatter_nocommute_gap ireduce_scatter_nocommute_gap_inter iscatter_gap_inter comm_idup_with_info

[TestRun:OSUInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:OSUInstalled
timeout = 600
test_dir = "mpi/pt2pt"
np = 2
stdout_save_lines = 1000
checkpoint_file = /ccs/home/howardp/mtt/master_scratch/ompi_logfile
