# INI file for Perlmutter

[MTTDefaults]
scratchdir = master_scratch
description = OpenMPI main
platform = LLNL-rzadams
executor = sequential
restart_file = /usr/workspace/hpp/mtt/master_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
#command = mpirun --display-allocation
command = mpirun
np = 2
ppn = 1

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:OSUInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:OSUInstalled
timeout = 600
test_dir = "c/mpi/pt2pt/standard"
checkpoint_file = /usr/workspace/hpp/mtt/master_scratch/ompi_logfile
stdout_save_lines = 1000
stderr_save_lines = 1000
skip_tests = osu_latency_mt

