# INI file for Perlmutter

[MTTDefaults]
scratchdir = v5.0.x_scratch
description = OpenMPI v5.0.x
platform = NERSC-perlmutter
executor = sequential
restart_file = /global/homes/h/hpp/mtt_perlmutter/v5.0.x_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
#command = mpirun --display-allocation
command = mpirun
np = 2
#ppn = 32

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:OSUInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:OSUInstalled
timeout = 600
test_dir = "mpi/pt2pt"
checkpoint_file = /global/homes/h/hpp/mtt_perlmutter/v5.0.x_scratch/ompi_logfile
stdout_save_lines = 1000
stderr_save_lines = 1000


