# INI file for rzadams

[MTTDefaults]
scratchdir = v6.0.x_scratch
description = OpenMPI v6.0.x
platform = LLNL-rzadams
executor = sequential
restart_file = /usr/workspace/hpp/mtt/v6.0.x_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
#command = mpirun --display-allocation
command = mpirun

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:OSUInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:OSUInstalled
timeout = 600
test_dir = "c/mpi/pt2pt/standard"
np = 2
ppn = 1
checkpoint_file = /usr/workspace/hpp/mtt/v6.0.x_scratch/ompi_logfile
stdout_save_lines = 1000
stderr_save_lines = 1000
skip_tests = osu_latency_mt

[TestRun:IBMInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:IBMInstalled
fail_timeout = 120
test_dir = "collective,pt2pt,random"
np = 4
#test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
checkpoint_file = /usr/workspace/hpp/mtt/v6.0.x_scratch/ompi_logfile
max_num_tests = 300
stdout_save_lines = 100
stderr_save_lines = 100

# Tests that are supposed to fail
fail_tests = abort:3 final:1


