# INI file for Perlmutter

[MTTDefaults]
scratchdir = master_scratch
description = OpenMPI master
platform = NERSC-perlmutter
executor = sequential
restart_file = /global/homes/h/hpp/mtt_perlmutter/master_scratch/ompi_logfile

[Profile:Installed]

#======================================================================
# Define some default launcher execution parameters
#======================================================================

[LauncherDefaults:OMPI]
plugin = OpenMPI
#plugin = ALPS
command = mpirun --display-allocation
np = 16

skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

#======================================================================
# Test run phase - the executor will automatically change directory to
# the top directory where the tests were installed, so any search for
# executables will take place relative to that point
#======================================================================

[TestRun:IBMInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:IBMInstalled
timeout = 120
test_dir = "collective, communicator, pt2pt, sessions, onesided"
#test_dir = "collective"
checkpoint_file = /global/homes/h/hpp/mtt_perlmutter/master_scratch/ompi_logfile
#test_dir = "communicator, datatype, environment, group, info, io, pt2pt, random, topology"
#max_num_tests = 10
stdout_save_lines = 100
stderr_save_lines = 100

# Tests that are supposed to fail
fail_tests = abort:3 final:1

skip_tests =  sendrecv_big sendrecv_rep_big  mprobe improbe mprobe-mpich mprobe_usempi mprobe_mpifh improbe_usempi mprobe_usempif08 improbe_usempif08 isendrecv_big isendrecv_rep_big isendrecv_rep_big2 sendrecv_rep_big2 int_overflow improbe_mpifh


[TestRun:OSUInstalledOMPI]
#plugin = ALPS
plugin = OpenMPI
parent = TestBuild:OSUInstalled
timeout = 600
test_dir = "mpi/pt2pt"
checkpoint_file = /global/homes/h/hpp/mtt_perlmutter/master_scratch/ompi_logfile
stdout_save_lines = 1000
stderr_save_lines = 1000


